### ISSUE TITLE
Domain npress.info expired

### ISSUE THREAD

**Issue by mkyral** [zbycz/npress#6]
Asi nejlíp odstranit tu zmínku z README.

**Comment by zbycz** [comment]
Díky. Změněno.

Doména už neměla smysl prodlužovat, obsah na ní je přesunut. 
CMS už má asi nejlepší za sebou, ale nějaký 15 webů na tom běží a nestěžujou si, ba naopak, tak github je důstnojným prostorem k dožití :-)
